# Generated by Django 3.1.2 on 2021-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
