# Generated by Django 4.1.2 on 2022-12-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
