# Generated by Django 4.1.2 on 2022-10-29 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_category_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pkid",
            field=models.BigAutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courserating",
            name="pkid",
            field=models.BigAutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="pkid",
            field=models.BigAutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
