# Generated by Django 4.1.2 on 2022-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="pricing",
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
