# Generated by Django 4.1.2 on 2022-10-29 19:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_pkid_courserating_pkid_lesson_pkid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=123,
                editable=False,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
