# Generated by Django 4.1.2 on 2023-01-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_pricing_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="last_video_watched",
        ),
    ]
