# Generated by Django 4.1.2 on 2022-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sluger",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
