# Generated by Django 4.1.2 on 2022-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_sluger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="sluger",
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
