# Generated by Django 4.1.2 on 2023-02-09 20:18

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_currency_course_is_private_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.currency",
            ),
        ),
    ]
