# Generated by Django 4.1.2 on 2023-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_watch_time",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="position",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="total_video_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="position",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="watchtime",
            name="stopped_at",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
