# Generated by Django 4.1.2 on 2022-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="embedded_video_link",
            field=models.CharField(default="sdsd", max_length=1000),
            preserve_default=False,
        ),
    ]
