# Generated by Django 4.1.2 on 2023-02-10 11:57

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("courses", "0009_alter_course_currency_delete_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
            ),
        ),
    ]
