# Generated by Django 4.1.2 on 2022-10-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_lesson_embedded_video_link_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonVideo",
            new_name="Video",
        ),
    ]
