# Generated by Django 4.1.2 on 2023-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_course_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_private",
            field=models.BooleanField(
                default=True, help_text="uncheck this box for your course to go public"
            ),
        ),
    ]
