# Generated by Django 4.1.2 on 2023-03-24 18:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_course_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=200),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
