# Generated by Django 4.1.2 on 2022-11-02 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_rename_lessonvideo_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Certificate", "Certificate"),
                            ("Paid", "Paid"),
                        ],
                        default="Free",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.AddField(
            model_name="course",
            name="pricing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.pricing",
            ),
        ),
    ]
