# Generated by Django 4.1.2 on 2022-11-02 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_pricing_remove_course_course_type_course_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Shirt"),
                            ("SW", "Sport wear"),
                            ("OW", "Outwear"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("S", "Shirt"), ("SW", "Sport wear"), ("OW", "Outwear")],
                max_length=20,
                null=True,
            ),
        ),
    ]
