# Generated by Django 4.1.2 on 2022-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_category_alter_course_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="ff", max_length=50),
            preserve_default=False,
        ),
    ]
