# Generated by Django 4.1.2 on 2022-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_category_options_remove_course_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
