# Generated by Django 4.1.2 on 2022-12-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="embedded_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(default="1", max_length=300),
            preserve_default=False,
        ),
    ]
