# Generated by Django 4.1.2 on 2022-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_remove_video_video_length_course_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="embedded_link",
        ),
        migrations.AddField(
            model_name="video",
            name="video_id",
            field=models.CharField(default="coZbOM6E47I", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
