# Generated by Django 4.1.2 on 2022-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_remove_video_embedded_link_video_video_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_duration",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
