# Generated by Django 4.1.2 on 2022-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_alter_course_duration_alter_video_video_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_duration",
            new_name="duration_seconds",
        ),
        migrations.AddField(
            model_name="video",
            name="duration_time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
