# Generated by Django 4.1.2 on 2022-12-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_rename_video_duration_video_duration_seconds_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="duration",
            new_name="total_watch_time",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="total_video_length",
        ),
        migrations.AddField(
            model_name="lesson",
            name="total_video_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
