# Generated by Django 4.1.2 on 2022-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_rename_duration_course_total_watch_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration_time",
            field=models.DurationField(blank=True, max_length=10, null=True),
        ),
    ]
