# Generated by Django 4.1.2 on 2022-12-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_watchtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_video_watched",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_video_watched",
                to="courses.video",
            ),
        ),
    ]
