# Generated by Django 4.1.2 on 2022-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0026_course_last_video_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchtime",
            name="stopped_at",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
