# Generated by Django 4.1.2 on 2022-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_alter_watchtime_stopped_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchtime",
            name="stopped_at",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
