# Generated by Django 4.1.2 on 2022-12-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_certificate"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdashboard",
            name="courses_enrolled",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses_enrolled",
                through="user.Enrollment",
                to="courses.course",
            ),
        ),
    ]
