# Generated by Django 4.1.2 on 2022-10-29 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="username"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="user_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "followers_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="followed", to="user.userprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
    ]
