# Generated by Django 4.1.2 on 2022-12-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_userdashboard_courses_enrolled_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="finished",
            new_name="completed",
        ),
    ]
