# Generated by Django 4.1.2 on 2022-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_enrollment_completed_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="completed_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
