# Generated by Django 4.1.2 on 2022-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_is_instructor_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
