# Generated by Django 4.1.2 on 2023-01-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_last_video_watched"),
        ("user", "0008_instructor_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_video_watched",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_video_watched",
                to="courses.video",
            ),
        ),
    ]
