# Generated by Django 4.1.2 on 2023-01-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_enrollment_last_video_watched"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="student",
            new_name="user_dashboard",
        ),
    ]
