# Generated by Django 4.1.2 on 2023-01-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_bankaccount_payout_delete_instructorprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payout",
            new_name="Withdraw",
        ),
    ]
