# Generated by Django 4.1.2 on 2023-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_payout_withdraw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdraw",
            name="comment",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="account_balance",
            field=models.IntegerField(default=0),
        ),
    ]
