# Generated by Django 4.1.2 on 2023-01-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_remove_withdraw_comment_bankaccount_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
