# Generated by Django 4.1.2 on 2023-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_withdraw_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
    ]
