# Generated by Django 4.1.2 on 2023-02-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("user", "0017_remove_instructor_user_remove_withdraw_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
            ),
        ),
    ]
