# Generated by Django 4.1.2 on 2024-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Normal", "Normal"),
                    ("Facebook", "Facebook"),
                    ("Google", "Google"),
                ],
                default="Normal",
                max_length=255,
                null=True,
            ),
        ),
    ]
