# Generated by Django 4.1.2 on 2024-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_user_signup_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
