# Generated by Django 4.1.2 on 2022-12-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_pricing_course_price"),
        ("order", "0003_cart_order_ordered_transaction_cart_orders_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pricing",
        ),
    ]
