# Generated by Django 4.1.2 on 2023-01-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_delete_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("payment_paystack", "PayStack"),
                    ("payment_rave", "Rave by Flutterwave"),
                ],
                default="payment_paystack",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
